# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/primoc/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/primoc/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so

PRODUCT_COPY_FILES += \
  vendor/htc/primoc/proprietary/bin/awb_camera:system/bin/awb_camera \
  vendor/htc/primoc/proprietary/bin/bma150_usr:system/bin/bma150_usr \
  vendor/htc/primoc/proprietary/bin/lsc_camera:system/bin/lsc_camera \
  vendor/htc/primoc/proprietary/bin/rmt_storage:system/bin/rmt_storage \
  vendor/htc/primoc/proprietary/etc/firmware/default.acdb:system/etc/firmware/default.acdb \
  vendor/htc/primoc/proprietary/etc/firmware/default_org.acdb:system/etc/firmware/default_org.acdb \
  vendor/htc/primoc/proprietary/etc/firmware/default_org_wb.acdb:system/etc/firmware/default_org_wb.acdb \
  vendor/htc/primoc/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
  vendor/htc/primoc/proprietary/lib/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
  vendor/htc/primoc/proprietary/etc/firmware/bcm4330.hcd:system/etc/firmware/bcm4330.hcd \
  vendor/htc/primoc/proprietary/lib/hw/camera.default.so:system/lib/hw/camera.default.so \
  vendor/htc/primoc/proprietary/lib/libcameraface.so:system/lib/libcameraface.so \
  vendor/htc/primoc/proprietary/lib/libcamerapp.so:system/lib/libcamerapp.so \
  vendor/htc/primoc/proprietary/lib/libgemini.so:system/lib/libgemini.so \
  vendor/htc/primoc/proprietary/lib/libmmcamera_rawchipproc.so:system/lib/libmmcamera_rawchipproc.so \
  vendor/htc/primoc/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
  vendor/htc/primoc/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
  vendor/htc/primoc/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
  vendor/htc/primoc/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
  vendor/htc/primoc/proprietary/lib/libposteffect.so:system/lib/libposteffect.so \
  vendor/htc/primoc/proprietary/lib/libchromatix_s5k4e5yx_default_video.so:system/lib/libchromatix_s5k4e5yx_default_video.so \
  vendor/htc/primoc/proprietary/lib/libchromatix_s5k4e5yx_hdr.so:system/lib/libchromatix_s5k4e5yx_hdr.so \
  vendor/htc/primoc/proprietary/lib/libchromatix_s5k4e5yx_hfr.so:system/lib/libchromatix_s5k4e5yx_hfr.so \
  vendor/htc/primoc/proprietary/lib/libchromatix_s5k4e5yx_hfr_4x.so:system/lib/libchromatix_s5k4e5yx_hfr_4x.so \
  vendor/htc/primoc/proprietary/lib/libchromatix_s5k4e5yx_preview.so:system/lib/libchromatix_s5k4e5yx_preview.so \
  vendor/htc/primoc/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
  vendor/htc/primoc/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
  vendor/htc/primoc/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
  vendor/htc/primoc/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
  vendor/htc/primoc/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
  vendor/htc/primoc/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
  vendor/htc/primoc/proprietary/lib/libgsl.so:system/lib/libgsl.so \
  vendor/htc/primoc/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
  vendor/htc/primoc/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
  vendor/htc/primoc/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
  vendor/htc/primoc/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
  vendor/htc/primoc/proprietary/etc/firmware/vidc_720p_command_control.fw:system/etc/firmware/vidc_720p_command_control.fw \
  vendor/htc/primoc/proprietary/etc/firmware/vidc_720p_h263_dec_mc.fw:system/etc/firmware/vidc_720p_h263_dec_mc.fw \
  vendor/htc/primoc/proprietary/etc/firmware/vidc_720p_h264_dec_mc.fw:system/etc/firmware/vidc_720p_h264_dec_mc.fw \
  vendor/htc/primoc/proprietary/etc/firmware/vidc_720p_h264_enc_mc.fw:system/etc/firmware/vidc_720p_h264_enc_mc.fw \
  vendor/htc/primoc/proprietary/etc/firmware/vidc_720p_mp4_dec_mc.fw:system/etc/firmware/vidc_720p_mp4_dec_mc.fw \
  vendor/htc/primoc/proprietary/etc/firmware/vidc_720p_mp4_enc_mc.fw:system/etc/firmware/vidc_720p_mp4_enc_mc.fw \
  vendor/htc/primoc/proprietary/etc/firmware/vidc_720p_vc1_dec_mc.fw:system/etc/firmware/vidc_720p_vc1_dec_mc.fw \
  vendor/htc/primoc/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
  vendor/htc/primoc/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
  vendor/htc/primoc/proprietary/lib/libdiag.so:system/lib/libdiag.so \
  vendor/htc/primoc/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
  vendor/htc/primoc/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
  vendor/htc/primoc/proprietary/lib/libidl.so:system/lib/libidl.so \
  vendor/htc/primoc/proprietary/lib/libqdp.so:system/lib/libqdp.so \
  vendor/htc/primoc/proprietary/lib/libqmi.so:system/lib/libqmi.so \
  vendor/htc/primoc/proprietary/lib/libhtc_ril.so:system/lib/libhtc_ril.so \
  vendor/htc/primoc/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
  vendor/htc/primoc/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
  vendor/htc/primoc/proprietary/etc/calibration:system/etc/calibration
